"""
Action Control Routes
Provides APIs to execute, monitor, and rollback AI actions
"""

import logging
from fastapi import APIRouter, HTTPException
from typing import Dict, Any

from services.action_execution_service import ActionExecutionService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/actions", tags=["Action Control"])

action_service = ActionExecutionService()


# ---------------------------------------------------------
# EXECUTE DECISION ACTIONS
# ---------------------------------------------------------
@router.post("/execute")
async def execute_actions(decision: Dict[str, Any]):
    """
    Executes actions generated by Decision Engine
    """

    try:
        result = action_service.execute_actions(decision)
        return {
            "status": "execution_completed",
            "execution_result": result
        }

    except Exception as e:
        logger.exception("Action execution endpoint failed")
        raise HTTPException(status_code=500, detail=str(e))


# ---------------------------------------------------------
# MANUAL SINGLE ACTION EXECUTION
# ---------------------------------------------------------
@router.post("/execute-single")
async def execute_single_action(action: Dict[str, Any]):
    """
    Execute a single manual action
    """

    try:
        decision = {
            "final_action": {
                "recommended_actions": [action]
            }
        }

        result = action_service.execute_actions(decision)

        return {
            "status": "single_action_executed",
            "result": result
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ---------------------------------------------------------
# EXECUTION HISTORY
# ---------------------------------------------------------
@router.get("/history")
async def execution_history():
    """
    Returns last 100 execution logs
    """

    try:
        return {
            "history": action_service.get_execution_history()
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ---------------------------------------------------------
# ROLLBACK LAST EXECUTION
# ---------------------------------------------------------
@router.post("/rollback")
async def rollback_last_execution():
    """
    Rolls back last executed action batch
    """

    try:
        result = action_service.rollback_last()
        return {
            "status": "rollback_processed",
            "result": result
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ---------------------------------------------------------
# ACTION SERVICE HEALTH
# ---------------------------------------------------------
@router.get("/health")
async def action_service_health():
    """
    Returns execution service health
    """

    try:
        return action_service.health_status()

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
